name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and Serve
        run: |
          # Thực hiện build hoặc các lệnh cần thiết cho dự án
          echo "Website built!"
